service: ParamStoreReplicator 

provider:
  name: aws
  runtime: nodejs16.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameters"
        - "ssm:GetParameter"
        - "ssm:PutParameter"
        - "ssm:DeleteParameter"
        - "ssm:DeleteParameters"
      Resource: "*"

functions:
  replicate:
    environment: 
      AWS_TARGET_REGION: ${param:target}
    handler: handler.replicate
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.ssm"
            detail-type:
              - "Parameter Store Change"