service: parameter-store-replicator 

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ssm:GetParameters"
            - "ssm:GetParameter"
            - "ssm:PutParameter"
            - "ssm:DeleteParameter"
            - "ssm:DeleteParameters"
          Resource: "*"
  environment: 
    AWS_TARGET_REGION: ${opt:target}

functions:
  replicate:
    handler: handler.replicate
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.ssm"
            detail-type:
              - "Parameter Store Change"

